export const ADD_TO_CART_REQUEST = "ADD_TO_CART_REQUEST";
export const DELETE_FROM_CART_REQUEST = "DELETE_FROM_CART_REQUEST";

export const ADD_TO_CART = "ADD_TO_CART";
export const DELETE_FROM_CART = "DELETE_FROM_CART";

export const ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCESS";
export const DELETE_FROM_CART_SUCCESS = "DELETE_FROM_CART_SUCCESS";
